### PR TITLE
Add git_diff_commit, git_diff_unstaged and preserve_unselected options

### PR DESCRIPTION
**Pull request by dehero**
There is a workflow when only changed files should be included in transport request. To get the list of files that were changed there are new `git_diff_commit` and `git_diff_unstaged` options. To keep not-changed files on server there's new `preserve_unselected` option. Here's the description:

**git_diff_commit**
Optional git commit, branch or reference to compare current state with. Will only upload files that were somehow changed (added, modified or deleted) since specified state.

**git_diff_unstaged**
Include unstaged files in git diff.

**preserve_unselected**
Don't delete files from BSP container, that were not selected to upload. Useful when using `git_diff_commit` option to keep unchanged files untouched.

### CODE REVIEW

**Comment by nrdev88** [comment]
Could you update package.json? I will then merge your PR and update the npm package

**Review by nrdev88 — APPROVED** [review]
Thanks! Approved 👍

**Comment by nrdev88** [comment]
FYI: released 1.1.0 on npm. Thanks again for the work

**Comment by dehero** [comment]
Great! Moving to npm version in my projects. Thank you for this tool.

**Pull request merged**
